### ISSUE TITLE
Using Nunjuck for create stati website with multiple pages

### ISSUE THREAD

**Issue by baglio** [tr1s/tris-webpack-boilerplate#16]
Hello, there,

I came across this fantastic boilerplate, and I'd like to use it for my future projects. I've previously used some pre-made webpack kickstarters, but to be honest I've never dug inside the config files.

I'd like to use nunjuck as my template engine in order to output several .html files to create static websites. I used Blendid, that didn't require to manually import new .html files inside the entry js file. Is it possibile to achieve something like this?

Thank you.

**Comment by AndreaPontrandolfo** [comment]
I'm in the same boat. I was using Blendid but i want to switch to this fantastic boilerplate. But Blendid used Nunjucks by default and now my projects are written in Nunjucks. The problem is, apparently html-webpack-plugin doesn't support nunjucks [https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md](apparently html-webpack-plugin doesn't support nunjucks?). Or am i misunderstanding something?

**Comment by tr1s** [comment]
@baglio @AndreaPontrandolfo html-webpack-plugin doesn't have nunchucks listed as supported, but it looks like [some people may have figured it out](https://github.com/at0g/nunjucks-loader/issues/35#issuecomment-335304596). Give this a shot!

**Comment by ogonkov** [comment]
Little self promotion: as alternative [simple-nunjucks-loader](https://www.npmjs.com/package/simple-nunjucks-loader) could be used.
